version: "3.9"
   
services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'my-gcd-db'
       MYSQL_USER: 'gcd-django'
       MYSQL_PASSWORD: 'db-gcd'
       MYSQL_ROOT_PASSWORD: 'root-password'
    volumes:
      - db:/var/lib/mysql
  web:
    build: .
    command: ./wait.sh
    volumes:
      - .:/gcd-django
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE=my-gcd-db
      - MYSQL_USER=gcd-django
      - MYSQL_PASSWORD=db-gcd
      - MYSQL_ROOT_PASSWORD=root-password 
    depends_on:
      - db
volumes:
  db:
    driver: local

